services:
  mantisbt:
    build: .
    container_name: mantisbt
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mantisbt
      MYSQL_USER: mantisbt_user
      MYSQL_PASSWORD: mantisbt_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
