# Use official Python image as a base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python program into the container
COPY arithmetic.py .

# Set the entry point to run the Python program
CMD ["python", "arithmetic.py"]
